image: node:18

pages:
  stage: deploy
  script:
    - mkdir .public || true
    - cp -r * .public || true
    - mkdir public || true
    - cp -r index.html public/
    - cp -r README.md public/
  artifacts:
    paths:
      - public
  only:
    - main
